version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm run webpack




artifacts:
  type:
    "s3"

  files:
    - index.html
    - favicon.ico
    - VanessaHensonResume.pdf
    - images/*
    - styles/*
    - dist/bundle.js
